#include QMK_KEYBOARD_H


enum unicode_names {
    YI_LOWER,
    YI_UPPER,
    CC_LOWER,
    CC_UPPER,
    UU_LOWER,
    UU_UPPER,
    KA_LOWER,
    KA_UPPER,
    EE_LOWER,
    EE_UPPER,
};

const uint32_t PROGMEM unicode_map[] = {
    [YI_LOWER] = 0x0439,
    [YI_UPPER] = 0x0419,
    [CC_LOWER] = 0x0446,
    [CC_UPPER] = 0x0426,
    [UU_LOWER] = 0x0443,
    [UU_UPPER] = 0x0423,
    [KA_LOWER] = 0x043A,
    [KA_UPPER] = 0x041A,
    [EE_LOWER] = 0x0435,
    [EE_UPPER] = 0x0415,
};

#define XP_YI XP(YI_LOWER, YI_UPPER)
#define XP_CC XP(CC_LOWER, CC_UPPER)
#define XP_UU XP(UU_LOWER, UU_UPPER)
#define XP_KA XP(KA_LOWER, KA_UPPER)
#define XP_EE XP(EE_LOWER, EE_UPPER)

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
        [0] = LAYOUT_split_3x5_3(KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, MO(2), MO(1), KC_LGUI, KC_RSFT, KC_SPC, MO(3)),
        [1] = LAYOUT_split_3x5_3(LCTL(KC_Q), LCTL(KC_W), LALT(KC_RGHT), LCTL(KC_R), LCTL(KC_T), LCTL(KC_Y), LCTL(KC_U), LCTL(KC_I), LCTL(KC_O), LCTL(KC_P), LCTL(KC_A), LCTL(KC_S), LCTL(KC_D), LCTL(KC_F), LCTL(KC_G), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_ESC, LCTL(KC_Z), LCTL(KC_X), LCTL(KC_C), LCTL(KC_V), LALT(KC_LEFT), LCTL(KC_N), KC_BSPC, LALT(KC_BSPC), LCTL(KC_DOT), LCTL(KC_ENT), KC_NO, KC_TRNS, KC_NO, KC_ENT, KC_TAB, LGUI(KC_RBRC)),
        [2] = LAYOUT_split_3x5_3(KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_EQL, KC_LBRC, KC_RBRC, KC_QUES, KC_GT, KC_CIRC, KC_UNDS, KC_PIPE, KC_DLR, KC_QUOT, KC_PLUS, KC_PIPE, KC_VOLD, KC_VOLU, KC_PERC, KC_GRV, KC_MINS, KC_LCBR, KC_RCBR, KC_TILD, KC_TRNS, MO(3), KC_LSFT, LCTL(KC_SPC), KC_SPC, LCTL(KC_SPC)),
        [3] = LAYOUT_split_3x5_3(KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_NO, TG(5), KC_NO, KC_SLSH, LAG(KC_H), LAG(KC_J), LAG(KC_K), LAG(KC_L), KC_DQUO, LAG(KC_Z), KC_F2, KC_F3, LAG(KC_V), KC_F5, KC_F6, KC_SLSH, KC_F8, KC_F9, KC_F10, KC_QUES, KC_LCTL, KC_LGUI, KC_SPC, KC_TRNS, KC_TRNS),
        [4] = LAYOUT_split_3x5_3(KC_NO, LALT(KC_Q), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F5, KC_NO, LAG(KC_H), LAG(KC_J), LAG(KC_K), LAG(KC_L), KC_CIRC, KC_F1, KC_F2, KC_F3, KC_F4, KC_NO, LAG(KC_Z), KC_NO, KC_NO, LAG(KC_D), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_LCTL, KC_NO, KC_TRNS, KC_NO, KC_NO),
        [5] = LAYOUT_split_3x5_3(XP_YI, XP_CC, XP_UU, XP_KA, XP_EE, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_A, KC_S, KC_D, KC_F, KC_G, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, MO(2), MO(1), KC_LGUI, KC_RSFT, KC_SPC, MO(3))
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)

