name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
# List of keymap json files to build
        file:
        - keymap.json
# End of json file list
        keyboard: [samoklava]
        conv: [stemcell]
        split: [left, right]
    steps:

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        submodules: recursive

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}
    
    - name: Setup variables
      env:
        conv_suffix: $([ ${{ matrix.conv }} ] && printf "_${{ matrix.conv }}")
        split_suffix: $([ ${{ matrix.split }} ] && printf "_${{ matrix.split }}")
      run: |
        echo "build_args=-e CONVERT_TO=${{ matrix.conv }} -e STMC_US=yes -e SPLIT=${{ matrix.split }}" >> $GITHUB_ENV 
        echo "file_suffix=${{ env.conv_suffix }}${{ env.split_suffix }}" >> $GITHUB_ENV
        echo "archive_name=${{ matrix.keyboard }}${{ env.conv_suffix }}" >> $GITHUB_ENV
  
      
    - name: Build firmware
      working-directory: users/${{ github.actor }}
      run: qmk -v compile -j 3 ${{ env.build_args }} ${{ matrix.file }}

    - name: Rename uf2
      if: ${{ matrix.conv != '' }}
      continue-on-error: true
      run: for file in *.uf2; do mv -v $file ${file%.*}${{ env.file_suffix }}.uf2; done
      
    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        retention-days: 30
        name: ${{ env.archive_name }}
        path: |
          *.hex
          *.bin
          *.uf2
